package com.bdqnsh.student.dao;

import com.bdqnsh.student.model.AdminRole;
import org.springframework.stereotype.Repository;

@Repository
public interface AdminRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    int insert(AdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    int insertSelective(AdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    AdminRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    int updateByPrimaryKeySelective(AdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    int updateByPrimaryKey(AdminRole record);
}