package com.bdqnsh.student.model;

import java.util.Date;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_name
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.nick_name
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.role_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.last_login_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Long createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.update_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Long updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.update_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.del_state
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Boolean delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_name
     *
     * @return the value of admin.user_name
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_name
     *
     * @param userName the value for admin.user_name
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.nick_name
     *
     * @return the value of admin.nick_name
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.nick_name
     *
     * @param nickName the value for admin.nick_name
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.role_id
     *
     * @return the value of admin.role_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.role_id
     *
     * @param roleId the value for admin.role_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.last_login_time
     *
     * @return the value of admin.last_login_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.last_login_time
     *
     * @param lastLoginTime the value for admin.last_login_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_id
     *
     * @return the value of admin.create_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_id
     *
     * @param createId the value for admin.create_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_time
     *
     * @return the value of admin.create_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_time
     *
     * @param createTime the value for admin.create_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.update_id
     *
     * @return the value of admin.update_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.update_id
     *
     * @param updateId the value for admin.update_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.update_time
     *
     * @return the value of admin.update_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.update_time
     *
     * @param updateTime the value for admin.update_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.del_state
     *
     * @return the value of admin.del_state
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Boolean getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.del_state
     *
     * @param delState the value for admin.del_state
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setDelState(Boolean delState) {
        this.delState = delState;
    }
}