package com.bdqnsh.student.model;

import java.util.Date;

public class AdminRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.admin_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.role_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.create_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.create_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.update_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.update_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role.del_state
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Boolean delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.id
     *
     * @return the value of admin_role.id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.id
     *
     * @param id the value for admin_role.id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.admin_id
     *
     * @return the value of admin_role.admin_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.admin_id
     *
     * @param adminId the value for admin_role.admin_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.role_id
     *
     * @return the value of admin_role.role_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.role_id
     *
     * @param roleId the value for admin_role.role_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.create_time
     *
     * @return the value of admin_role.create_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.create_time
     *
     * @param createTime the value for admin_role.create_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.create_id
     *
     * @return the value of admin_role.create_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.create_id
     *
     * @param createId the value for admin_role.create_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.update_id
     *
     * @return the value of admin_role.update_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.update_id
     *
     * @param updateId the value for admin_role.update_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.update_time
     *
     * @return the value of admin_role.update_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.update_time
     *
     * @param updateTime the value for admin_role.update_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_role.del_state
     *
     * @return the value of admin_role.del_state
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Boolean getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_role.del_state
     *
     * @param delState the value for admin_role.del_state
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setDelState(Boolean delState) {
        this.delState = delState;
    }
}