package com.bdqnsh.student.model;

import java.util.Date;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.name
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.url
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.create_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.create_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.update_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.update_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.del_state
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Boolean delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.name
     *
     * @return the value of resource.name
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.name
     *
     * @param name the value for resource.name
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.url
     *
     * @return the value of resource.url
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.url
     *
     * @param url the value for resource.url
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.create_id
     *
     * @return the value of resource.create_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.create_id
     *
     * @param createId the value for resource.create_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.create_time
     *
     * @return the value of resource.create_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.create_time
     *
     * @param createTime the value for resource.create_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.update_id
     *
     * @return the value of resource.update_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.update_id
     *
     * @param updateId the value for resource.update_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.update_time
     *
     * @return the value of resource.update_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.update_time
     *
     * @param updateTime the value for resource.update_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.del_state
     *
     * @return the value of resource.del_state
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Boolean getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.del_state
     *
     * @param delState the value for resource.del_state
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setDelState(Boolean delState) {
        this.delState = delState;
    }
}