package com.bdqnsh.student.model;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.create_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Long createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.create_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.update_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Long updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.update_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.del_state
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    private Boolean delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.create_id
     *
     * @return the value of role.create_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_id
     *
     * @param createId the value for role.create_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.create_time
     *
     * @return the value of role.create_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_time
     *
     * @param createTime the value for role.create_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.update_id
     *
     * @return the value of role.update_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.update_id
     *
     * @param updateId the value for role.update_id
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.update_time
     *
     * @return the value of role.update_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.update_time
     *
     * @param updateTime the value for role.update_time
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.del_state
     *
     * @return the value of role.del_state
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public Boolean getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.del_state
     *
     * @param delState the value for role.del_state
     *
     * @mbggenerated Thu Apr 27 16:07:40 CST 2017
     */
    public void setDelState(Boolean delState) {
        this.delState = delState;
    }
}