package com.bdqnsh.student.model;

import java.util.Date;

public class RoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.role_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.resource_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.create_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.create_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.update_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Long updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.update_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.del_state
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    private Boolean delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.id
     *
     * @return the value of role_resource.id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.id
     *
     * @param id the value for role_resource.id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.role_id
     *
     * @return the value of role_resource.role_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.role_id
     *
     * @param roleId the value for role_resource.role_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.resource_id
     *
     * @return the value of role_resource.resource_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.resource_id
     *
     * @param resourceId the value for role_resource.resource_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.create_id
     *
     * @return the value of role_resource.create_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.create_id
     *
     * @param createId the value for role_resource.create_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.create_time
     *
     * @return the value of role_resource.create_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.create_time
     *
     * @param createTime the value for role_resource.create_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.update_id
     *
     * @return the value of role_resource.update_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.update_id
     *
     * @param updateId the value for role_resource.update_id
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.update_time
     *
     * @return the value of role_resource.update_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.update_time
     *
     * @param updateTime the value for role_resource.update_time
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.del_state
     *
     * @return the value of role_resource.del_state
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public Boolean getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.del_state
     *
     * @param delState the value for role_resource.del_state
     *
     * @mbggenerated Mon May 08 15:46:49 CST 2017
     */
    public void setDelState(Boolean delState) {
        this.delState = delState;
    }
}