package com.bdqnsh.student.model;

import java.math.BigDecimal;
import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Boolean gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.birthday
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.blood_type
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String bloodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.constellation
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String constellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.religion
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String religion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.father_name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String fatherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mother_name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String motherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.father_birthday
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Date fatherBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mother_birthday
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Date motherBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.telephone
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mobile
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.info_source
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String infoSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.emergency_contact
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String emergencyContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.emergency_contact_phone
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String emergencyContactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.qq
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.email
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.wechat
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.identity_card
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ancestral_home
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String ancestralHome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.vehicle
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String vehicle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.address
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.post_code
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.cost_source
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String costSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.computer_basis
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String computerBasis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.soft_basis
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String softBasis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.computer_operate
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String computerOperate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.language_skill
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String languageSkill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.expectation
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String expectation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_teacher_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Long classTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Long classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.teacher_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.counselor_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Long counselorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.hobby
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.record_number
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String recordNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_time
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Long createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.update_time
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.update_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Long updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.del_state
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Boolean delState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.payment
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.compony
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String compony;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.work_type
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String workType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.off_job
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String offJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.in_school_name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String inSchoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.highest_degree
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String highestDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.major
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.school
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.occupation
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.process
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Integer process;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.company1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String company1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.work_date1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String workDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.position1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String position1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.work_content1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String workContent1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.company2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String company2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.work_date2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String workDate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.position2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String position2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.work_content2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String workContent2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.company3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String company3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.work_date3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String workDate3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.position3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String position3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.work_content3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String workContent3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.club
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String club;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.idol
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String idol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.idea
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String idea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.activity
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String activity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.technology
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String technology;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.technology_index
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Integer technologyIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.commomweal
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Boolean commomweal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.commomweal_date
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String commomwealDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.commomweal_area
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String commomwealArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.commomweal_content
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String commomwealContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.commomweal_will
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Boolean commomwealWill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.online_game
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Boolean onlineGame;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.game_name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String gameName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.game_level
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String gameLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.game_team
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String gameTeam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mate_type
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String mateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.is_computer_major
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private Boolean isComputerMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_company1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String trainingCompany1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_date1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String trainingDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_industry1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String trainingIndustry1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_content1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String trainingContent1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_company2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String trainingCompany2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_date2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String trainingDate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_industry2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String trainingIndustry2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_content2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String trainingContent2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_company3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String trainingCompany3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_date3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String trainingDate3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_industry3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String trainingIndustry3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.training_content3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String trainingContent3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.technology_friends
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    private String technologyFriends;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.birthday
     *
     * @return the value of student.birthday
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.birthday
     *
     * @param birthday the value for student.birthday
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.blood_type
     *
     * @return the value of student.blood_type
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.blood_type
     *
     * @param bloodType the value for student.blood_type
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.constellation
     *
     * @return the value of student.constellation
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getConstellation() {
        return constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.constellation
     *
     * @param constellation the value for student.constellation
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setConstellation(String constellation) {
        this.constellation = constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.religion
     *
     * @return the value of student.religion
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getReligion() {
        return religion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.religion
     *
     * @param religion the value for student.religion
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setReligion(String religion) {
        this.religion = religion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.father_name
     *
     * @return the value of student.father_name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getFatherName() {
        return fatherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.father_name
     *
     * @param fatherName the value for student.father_name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mother_name
     *
     * @return the value of student.mother_name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getMotherName() {
        return motherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mother_name
     *
     * @param motherName the value for student.mother_name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.father_birthday
     *
     * @return the value of student.father_birthday
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Date getFatherBirthday() {
        return fatherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.father_birthday
     *
     * @param fatherBirthday the value for student.father_birthday
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setFatherBirthday(Date fatherBirthday) {
        this.fatherBirthday = fatherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mother_birthday
     *
     * @return the value of student.mother_birthday
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Date getMotherBirthday() {
        return motherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mother_birthday
     *
     * @param motherBirthday the value for student.mother_birthday
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setMotherBirthday(Date motherBirthday) {
        this.motherBirthday = motherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.telephone
     *
     * @return the value of student.telephone
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.telephone
     *
     * @param telephone the value for student.telephone
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mobile
     *
     * @return the value of student.mobile
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mobile
     *
     * @param mobile the value for student.mobile
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.info_source
     *
     * @return the value of student.info_source
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getInfoSource() {
        return infoSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.info_source
     *
     * @param infoSource the value for student.info_source
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setInfoSource(String infoSource) {
        this.infoSource = infoSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.emergency_contact
     *
     * @return the value of student.emergency_contact
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getEmergencyContact() {
        return emergencyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.emergency_contact
     *
     * @param emergencyContact the value for student.emergency_contact
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setEmergencyContact(String emergencyContact) {
        this.emergencyContact = emergencyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.emergency_contact_phone
     *
     * @return the value of student.emergency_contact_phone
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getEmergencyContactPhone() {
        return emergencyContactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.emergency_contact_phone
     *
     * @param emergencyContactPhone the value for student.emergency_contact_phone
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setEmergencyContactPhone(String emergencyContactPhone) {
        this.emergencyContactPhone = emergencyContactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.qq
     *
     * @return the value of student.qq
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.qq
     *
     * @param qq the value for student.qq
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.email
     *
     * @return the value of student.email
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.email
     *
     * @param email the value for student.email
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.wechat
     *
     * @return the value of student.wechat
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.wechat
     *
     * @param wechat the value for student.wechat
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.identity_card
     *
     * @return the value of student.identity_card
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.identity_card
     *
     * @param identityCard the value for student.identity_card
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ancestral_home
     *
     * @return the value of student.ancestral_home
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getAncestralHome() {
        return ancestralHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ancestral_home
     *
     * @param ancestralHome the value for student.ancestral_home
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setAncestralHome(String ancestralHome) {
        this.ancestralHome = ancestralHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.vehicle
     *
     * @return the value of student.vehicle
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.vehicle
     *
     * @param vehicle the value for student.vehicle
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setVehicle(String vehicle) {
        this.vehicle = vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.address
     *
     * @return the value of student.address
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.address
     *
     * @param address the value for student.address
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.post_code
     *
     * @return the value of student.post_code
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.post_code
     *
     * @param postCode the value for student.post_code
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.cost_source
     *
     * @return the value of student.cost_source
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getCostSource() {
        return costSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.cost_source
     *
     * @param costSource the value for student.cost_source
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCostSource(String costSource) {
        this.costSource = costSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.computer_basis
     *
     * @return the value of student.computer_basis
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getComputerBasis() {
        return computerBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.computer_basis
     *
     * @param computerBasis the value for student.computer_basis
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setComputerBasis(String computerBasis) {
        this.computerBasis = computerBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.soft_basis
     *
     * @return the value of student.soft_basis
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getSoftBasis() {
        return softBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.soft_basis
     *
     * @param softBasis the value for student.soft_basis
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setSoftBasis(String softBasis) {
        this.softBasis = softBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.computer_operate
     *
     * @return the value of student.computer_operate
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getComputerOperate() {
        return computerOperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.computer_operate
     *
     * @param computerOperate the value for student.computer_operate
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setComputerOperate(String computerOperate) {
        this.computerOperate = computerOperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.language_skill
     *
     * @return the value of student.language_skill
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getLanguageSkill() {
        return languageSkill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.language_skill
     *
     * @param languageSkill the value for student.language_skill
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setLanguageSkill(String languageSkill) {
        this.languageSkill = languageSkill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.expectation
     *
     * @return the value of student.expectation
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getExpectation() {
        return expectation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.expectation
     *
     * @param expectation the value for student.expectation
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setExpectation(String expectation) {
        this.expectation = expectation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_teacher_id
     *
     * @return the value of student.class_teacher_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Long getClassTeacherId() {
        return classTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_teacher_id
     *
     * @param classTeacherId the value for student.class_teacher_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setClassTeacherId(Long classTeacherId) {
        this.classTeacherId = classTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_id
     *
     * @return the value of student.class_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_id
     *
     * @param classId the value for student.class_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.teacher_id
     *
     * @return the value of student.teacher_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.teacher_id
     *
     * @param teacherId the value for student.teacher_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.counselor_id
     *
     * @return the value of student.counselor_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Long getCounselorId() {
        return counselorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.counselor_id
     *
     * @param counselorId the value for student.counselor_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCounselorId(Long counselorId) {
        this.counselorId = counselorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.hobby
     *
     * @return the value of student.hobby
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.hobby
     *
     * @param hobby the value for student.hobby
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.record_number
     *
     * @return the value of student.record_number
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getRecordNumber() {
        return recordNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.record_number
     *
     * @param recordNumber the value for student.record_number
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setRecordNumber(String recordNumber) {
        this.recordNumber = recordNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_time
     *
     * @return the value of student.create_time
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_time
     *
     * @param createTime the value for student.create_time
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_id
     *
     * @return the value of student.create_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_id
     *
     * @param createId the value for student.create_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.update_time
     *
     * @return the value of student.update_time
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.update_time
     *
     * @param updateTime the value for student.update_time
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.update_id
     *
     * @return the value of student.update_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.update_id
     *
     * @param updateId the value for student.update_id
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.del_state
     *
     * @return the value of student.del_state
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Boolean getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.del_state
     *
     * @param delState the value for student.del_state
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setDelState(Boolean delState) {
        this.delState = delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.payment
     *
     * @return the value of student.payment
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.payment
     *
     * @param payment the value for student.payment
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.compony
     *
     * @return the value of student.compony
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getCompony() {
        return compony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.compony
     *
     * @param compony the value for student.compony
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCompony(String compony) {
        this.compony = compony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.work_type
     *
     * @return the value of student.work_type
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.work_type
     *
     * @param workType the value for student.work_type
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setWorkType(String workType) {
        this.workType = workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.off_job
     *
     * @return the value of student.off_job
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getOffJob() {
        return offJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.off_job
     *
     * @param offJob the value for student.off_job
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setOffJob(String offJob) {
        this.offJob = offJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.in_school_name
     *
     * @return the value of student.in_school_name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getInSchoolName() {
        return inSchoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.in_school_name
     *
     * @param inSchoolName the value for student.in_school_name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setInSchoolName(String inSchoolName) {
        this.inSchoolName = inSchoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.highest_degree
     *
     * @return the value of student.highest_degree
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getHighestDegree() {
        return highestDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.highest_degree
     *
     * @param highestDegree the value for student.highest_degree
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setHighestDegree(String highestDegree) {
        this.highestDegree = highestDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.major
     *
     * @return the value of student.major
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.major
     *
     * @param major the value for student.major
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.school
     *
     * @return the value of student.school
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.school
     *
     * @param school the value for student.school
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.occupation
     *
     * @return the value of student.occupation
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.occupation
     *
     * @param occupation the value for student.occupation
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.process
     *
     * @return the value of student.process
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Integer getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.process
     *
     * @param process the value for student.process
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setProcess(Integer process) {
        this.process = process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.company1
     *
     * @return the value of student.company1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getCompany1() {
        return company1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.company1
     *
     * @param company1 the value for student.company1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCompany1(String company1) {
        this.company1 = company1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.work_date1
     *
     * @return the value of student.work_date1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getWorkDate1() {
        return workDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.work_date1
     *
     * @param workDate1 the value for student.work_date1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setWorkDate1(String workDate1) {
        this.workDate1 = workDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.position1
     *
     * @return the value of student.position1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getPosition1() {
        return position1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.position1
     *
     * @param position1 the value for student.position1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setPosition1(String position1) {
        this.position1 = position1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.work_content1
     *
     * @return the value of student.work_content1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getWorkContent1() {
        return workContent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.work_content1
     *
     * @param workContent1 the value for student.work_content1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setWorkContent1(String workContent1) {
        this.workContent1 = workContent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.company2
     *
     * @return the value of student.company2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getCompany2() {
        return company2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.company2
     *
     * @param company2 the value for student.company2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCompany2(String company2) {
        this.company2 = company2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.work_date2
     *
     * @return the value of student.work_date2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getWorkDate2() {
        return workDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.work_date2
     *
     * @param workDate2 the value for student.work_date2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setWorkDate2(String workDate2) {
        this.workDate2 = workDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.position2
     *
     * @return the value of student.position2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getPosition2() {
        return position2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.position2
     *
     * @param position2 the value for student.position2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setPosition2(String position2) {
        this.position2 = position2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.work_content2
     *
     * @return the value of student.work_content2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getWorkContent2() {
        return workContent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.work_content2
     *
     * @param workContent2 the value for student.work_content2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setWorkContent2(String workContent2) {
        this.workContent2 = workContent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.company3
     *
     * @return the value of student.company3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getCompany3() {
        return company3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.company3
     *
     * @param company3 the value for student.company3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCompany3(String company3) {
        this.company3 = company3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.work_date3
     *
     * @return the value of student.work_date3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getWorkDate3() {
        return workDate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.work_date3
     *
     * @param workDate3 the value for student.work_date3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setWorkDate3(String workDate3) {
        this.workDate3 = workDate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.position3
     *
     * @return the value of student.position3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getPosition3() {
        return position3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.position3
     *
     * @param position3 the value for student.position3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setPosition3(String position3) {
        this.position3 = position3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.work_content3
     *
     * @return the value of student.work_content3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getWorkContent3() {
        return workContent3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.work_content3
     *
     * @param workContent3 the value for student.work_content3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setWorkContent3(String workContent3) {
        this.workContent3 = workContent3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.club
     *
     * @return the value of student.club
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getClub() {
        return club;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.club
     *
     * @param club the value for student.club
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setClub(String club) {
        this.club = club;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.idol
     *
     * @return the value of student.idol
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getIdol() {
        return idol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.idol
     *
     * @param idol the value for student.idol
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setIdol(String idol) {
        this.idol = idol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.idea
     *
     * @return the value of student.idea
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getIdea() {
        return idea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.idea
     *
     * @param idea the value for student.idea
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setIdea(String idea) {
        this.idea = idea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.activity
     *
     * @return the value of student.activity
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.activity
     *
     * @param activity the value for student.activity
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setActivity(String activity) {
        this.activity = activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.technology
     *
     * @return the value of student.technology
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTechnology() {
        return technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.technology
     *
     * @param technology the value for student.technology
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTechnology(String technology) {
        this.technology = technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.technology_index
     *
     * @return the value of student.technology_index
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Integer getTechnologyIndex() {
        return technologyIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.technology_index
     *
     * @param technologyIndex the value for student.technology_index
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTechnologyIndex(Integer technologyIndex) {
        this.technologyIndex = technologyIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.commomweal
     *
     * @return the value of student.commomweal
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Boolean getCommomweal() {
        return commomweal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.commomweal
     *
     * @param commomweal the value for student.commomweal
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCommomweal(Boolean commomweal) {
        this.commomweal = commomweal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.commomweal_date
     *
     * @return the value of student.commomweal_date
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getCommomwealDate() {
        return commomwealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.commomweal_date
     *
     * @param commomwealDate the value for student.commomweal_date
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCommomwealDate(String commomwealDate) {
        this.commomwealDate = commomwealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.commomweal_area
     *
     * @return the value of student.commomweal_area
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getCommomwealArea() {
        return commomwealArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.commomweal_area
     *
     * @param commomwealArea the value for student.commomweal_area
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCommomwealArea(String commomwealArea) {
        this.commomwealArea = commomwealArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.commomweal_content
     *
     * @return the value of student.commomweal_content
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getCommomwealContent() {
        return commomwealContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.commomweal_content
     *
     * @param commomwealContent the value for student.commomweal_content
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCommomwealContent(String commomwealContent) {
        this.commomwealContent = commomwealContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.commomweal_will
     *
     * @return the value of student.commomweal_will
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Boolean getCommomwealWill() {
        return commomwealWill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.commomweal_will
     *
     * @param commomwealWill the value for student.commomweal_will
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setCommomwealWill(Boolean commomwealWill) {
        this.commomwealWill = commomwealWill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.online_game
     *
     * @return the value of student.online_game
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Boolean getOnlineGame() {
        return onlineGame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.online_game
     *
     * @param onlineGame the value for student.online_game
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setOnlineGame(Boolean onlineGame) {
        this.onlineGame = onlineGame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.game_name
     *
     * @return the value of student.game_name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getGameName() {
        return gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.game_name
     *
     * @param gameName the value for student.game_name
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.game_level
     *
     * @return the value of student.game_level
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getGameLevel() {
        return gameLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.game_level
     *
     * @param gameLevel the value for student.game_level
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setGameLevel(String gameLevel) {
        this.gameLevel = gameLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.game_team
     *
     * @return the value of student.game_team
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getGameTeam() {
        return gameTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.game_team
     *
     * @param gameTeam the value for student.game_team
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setGameTeam(String gameTeam) {
        this.gameTeam = gameTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mate_type
     *
     * @return the value of student.mate_type
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getMateType() {
        return mateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mate_type
     *
     * @param mateType the value for student.mate_type
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setMateType(String mateType) {
        this.mateType = mateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.is_computer_major
     *
     * @return the value of student.is_computer_major
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public Boolean getIsComputerMajor() {
        return isComputerMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.is_computer_major
     *
     * @param isComputerMajor the value for student.is_computer_major
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setIsComputerMajor(Boolean isComputerMajor) {
        this.isComputerMajor = isComputerMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_company1
     *
     * @return the value of student.training_company1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTrainingCompany1() {
        return trainingCompany1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_company1
     *
     * @param trainingCompany1 the value for student.training_company1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTrainingCompany1(String trainingCompany1) {
        this.trainingCompany1 = trainingCompany1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_date1
     *
     * @return the value of student.training_date1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTrainingDate1() {
        return trainingDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_date1
     *
     * @param trainingDate1 the value for student.training_date1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTrainingDate1(String trainingDate1) {
        this.trainingDate1 = trainingDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_industry1
     *
     * @return the value of student.training_industry1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTrainingIndustry1() {
        return trainingIndustry1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_industry1
     *
     * @param trainingIndustry1 the value for student.training_industry1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTrainingIndustry1(String trainingIndustry1) {
        this.trainingIndustry1 = trainingIndustry1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_content1
     *
     * @return the value of student.training_content1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTrainingContent1() {
        return trainingContent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_content1
     *
     * @param trainingContent1 the value for student.training_content1
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTrainingContent1(String trainingContent1) {
        this.trainingContent1 = trainingContent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_company2
     *
     * @return the value of student.training_company2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTrainingCompany2() {
        return trainingCompany2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_company2
     *
     * @param trainingCompany2 the value for student.training_company2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTrainingCompany2(String trainingCompany2) {
        this.trainingCompany2 = trainingCompany2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_date2
     *
     * @return the value of student.training_date2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTrainingDate2() {
        return trainingDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_date2
     *
     * @param trainingDate2 the value for student.training_date2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTrainingDate2(String trainingDate2) {
        this.trainingDate2 = trainingDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_industry2
     *
     * @return the value of student.training_industry2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTrainingIndustry2() {
        return trainingIndustry2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_industry2
     *
     * @param trainingIndustry2 the value for student.training_industry2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTrainingIndustry2(String trainingIndustry2) {
        this.trainingIndustry2 = trainingIndustry2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_content2
     *
     * @return the value of student.training_content2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTrainingContent2() {
        return trainingContent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_content2
     *
     * @param trainingContent2 the value for student.training_content2
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTrainingContent2(String trainingContent2) {
        this.trainingContent2 = trainingContent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_company3
     *
     * @return the value of student.training_company3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTrainingCompany3() {
        return trainingCompany3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_company3
     *
     * @param trainingCompany3 the value for student.training_company3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTrainingCompany3(String trainingCompany3) {
        this.trainingCompany3 = trainingCompany3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_date3
     *
     * @return the value of student.training_date3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTrainingDate3() {
        return trainingDate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_date3
     *
     * @param trainingDate3 the value for student.training_date3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTrainingDate3(String trainingDate3) {
        this.trainingDate3 = trainingDate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_industry3
     *
     * @return the value of student.training_industry3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTrainingIndustry3() {
        return trainingIndustry3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_industry3
     *
     * @param trainingIndustry3 the value for student.training_industry3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTrainingIndustry3(String trainingIndustry3) {
        this.trainingIndustry3 = trainingIndustry3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.training_content3
     *
     * @return the value of student.training_content3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTrainingContent3() {
        return trainingContent3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.training_content3
     *
     * @param trainingContent3 the value for student.training_content3
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTrainingContent3(String trainingContent3) {
        this.trainingContent3 = trainingContent3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.technology_friends
     *
     * @return the value of student.technology_friends
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public String getTechnologyFriends() {
        return technologyFriends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.technology_friends
     *
     * @param technologyFriends the value for student.technology_friends
     *
     * @mbggenerated Tue May 09 18:16:23 CST 2017
     */
    public void setTechnologyFriends(String technologyFriends) {
        this.technologyFriends = technologyFriends;
    }
}