package com.bdqnsh.student.model;

import java.math.BigDecimal;
import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Boolean gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.birthday
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.blood_type
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String bloodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.constellation
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String constellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.religion
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String religion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.father_name
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String fatherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mother_name
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String motherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.father_birthday
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Date fatherBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mother_birthday
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Date motherBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.telephone
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mobile
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.info_source
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String infoSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.emergency_contact
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String emergencyContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.emergency_contact_phone
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String emergencyContactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.qq
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.email
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.wechat
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.identity_card
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ancestral_home
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String ancestralHome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.vehicle
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String vehicle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.address
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.post_code
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.cost_source
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String costSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.computer_basis
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String computerBasis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.soft_basis
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String softBasis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.computer_operate
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String computerOperate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.language_skill
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String languageSkill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.expectation
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String expectation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_teacher_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Long classTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Long classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.hobby
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.counselor_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Long counselorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.record_number
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String recordNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_time
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Long createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.update_time
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.update_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Long updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.del_state
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Boolean delState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.payment
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.compony
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String compony;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.work_type
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String workType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.off_job
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String offJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.in_school_name
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String inSchoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.highest_degree
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String highestDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.major
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.school
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.occupation
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.process
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    private Integer process;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.birthday
     *
     * @return the value of student.birthday
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.birthday
     *
     * @param birthday the value for student.birthday
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.blood_type
     *
     * @return the value of student.blood_type
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.blood_type
     *
     * @param bloodType the value for student.blood_type
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.constellation
     *
     * @return the value of student.constellation
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getConstellation() {
        return constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.constellation
     *
     * @param constellation the value for student.constellation
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setConstellation(String constellation) {
        this.constellation = constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.religion
     *
     * @return the value of student.religion
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getReligion() {
        return religion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.religion
     *
     * @param religion the value for student.religion
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setReligion(String religion) {
        this.religion = religion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.father_name
     *
     * @return the value of student.father_name
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getFatherName() {
        return fatherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.father_name
     *
     * @param fatherName the value for student.father_name
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mother_name
     *
     * @return the value of student.mother_name
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getMotherName() {
        return motherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mother_name
     *
     * @param motherName the value for student.mother_name
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.father_birthday
     *
     * @return the value of student.father_birthday
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Date getFatherBirthday() {
        return fatherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.father_birthday
     *
     * @param fatherBirthday the value for student.father_birthday
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setFatherBirthday(Date fatherBirthday) {
        this.fatherBirthday = fatherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mother_birthday
     *
     * @return the value of student.mother_birthday
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Date getMotherBirthday() {
        return motherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mother_birthday
     *
     * @param motherBirthday the value for student.mother_birthday
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setMotherBirthday(Date motherBirthday) {
        this.motherBirthday = motherBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.telephone
     *
     * @return the value of student.telephone
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.telephone
     *
     * @param telephone the value for student.telephone
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mobile
     *
     * @return the value of student.mobile
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mobile
     *
     * @param mobile the value for student.mobile
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.info_source
     *
     * @return the value of student.info_source
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getInfoSource() {
        return infoSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.info_source
     *
     * @param infoSource the value for student.info_source
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setInfoSource(String infoSource) {
        this.infoSource = infoSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.emergency_contact
     *
     * @return the value of student.emergency_contact
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getEmergencyContact() {
        return emergencyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.emergency_contact
     *
     * @param emergencyContact the value for student.emergency_contact
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setEmergencyContact(String emergencyContact) {
        this.emergencyContact = emergencyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.emergency_contact_phone
     *
     * @return the value of student.emergency_contact_phone
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getEmergencyContactPhone() {
        return emergencyContactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.emergency_contact_phone
     *
     * @param emergencyContactPhone the value for student.emergency_contact_phone
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setEmergencyContactPhone(String emergencyContactPhone) {
        this.emergencyContactPhone = emergencyContactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.qq
     *
     * @return the value of student.qq
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.qq
     *
     * @param qq the value for student.qq
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.email
     *
     * @return the value of student.email
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.email
     *
     * @param email the value for student.email
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.wechat
     *
     * @return the value of student.wechat
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.wechat
     *
     * @param wechat the value for student.wechat
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.identity_card
     *
     * @return the value of student.identity_card
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.identity_card
     *
     * @param identityCard the value for student.identity_card
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ancestral_home
     *
     * @return the value of student.ancestral_home
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getAncestralHome() {
        return ancestralHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ancestral_home
     *
     * @param ancestralHome the value for student.ancestral_home
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setAncestralHome(String ancestralHome) {
        this.ancestralHome = ancestralHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.vehicle
     *
     * @return the value of student.vehicle
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.vehicle
     *
     * @param vehicle the value for student.vehicle
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setVehicle(String vehicle) {
        this.vehicle = vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.address
     *
     * @return the value of student.address
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.address
     *
     * @param address the value for student.address
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.post_code
     *
     * @return the value of student.post_code
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.post_code
     *
     * @param postCode the value for student.post_code
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.cost_source
     *
     * @return the value of student.cost_source
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getCostSource() {
        return costSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.cost_source
     *
     * @param costSource the value for student.cost_source
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setCostSource(String costSource) {
        this.costSource = costSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.computer_basis
     *
     * @return the value of student.computer_basis
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getComputerBasis() {
        return computerBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.computer_basis
     *
     * @param computerBasis the value for student.computer_basis
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setComputerBasis(String computerBasis) {
        this.computerBasis = computerBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.soft_basis
     *
     * @return the value of student.soft_basis
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getSoftBasis() {
        return softBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.soft_basis
     *
     * @param softBasis the value for student.soft_basis
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setSoftBasis(String softBasis) {
        this.softBasis = softBasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.computer_operate
     *
     * @return the value of student.computer_operate
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getComputerOperate() {
        return computerOperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.computer_operate
     *
     * @param computerOperate the value for student.computer_operate
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setComputerOperate(String computerOperate) {
        this.computerOperate = computerOperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.language_skill
     *
     * @return the value of student.language_skill
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getLanguageSkill() {
        return languageSkill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.language_skill
     *
     * @param languageSkill the value for student.language_skill
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setLanguageSkill(String languageSkill) {
        this.languageSkill = languageSkill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.expectation
     *
     * @return the value of student.expectation
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getExpectation() {
        return expectation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.expectation
     *
     * @param expectation the value for student.expectation
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setExpectation(String expectation) {
        this.expectation = expectation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_teacher_id
     *
     * @return the value of student.class_teacher_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Long getClassTeacherId() {
        return classTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_teacher_id
     *
     * @param classTeacherId the value for student.class_teacher_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setClassTeacherId(Long classTeacherId) {
        this.classTeacherId = classTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_id
     *
     * @return the value of student.class_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_id
     *
     * @param classId the value for student.class_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.hobby
     *
     * @return the value of student.hobby
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.hobby
     *
     * @param hobby the value for student.hobby
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.counselor_id
     *
     * @return the value of student.counselor_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Long getCounselorId() {
        return counselorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.counselor_id
     *
     * @param counselorId the value for student.counselor_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setCounselorId(Long counselorId) {
        this.counselorId = counselorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.record_number
     *
     * @return the value of student.record_number
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getRecordNumber() {
        return recordNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.record_number
     *
     * @param recordNumber the value for student.record_number
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setRecordNumber(String recordNumber) {
        this.recordNumber = recordNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_time
     *
     * @return the value of student.create_time
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_time
     *
     * @param createTime the value for student.create_time
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_id
     *
     * @return the value of student.create_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_id
     *
     * @param createId the value for student.create_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.update_time
     *
     * @return the value of student.update_time
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.update_time
     *
     * @param updateTime the value for student.update_time
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.update_id
     *
     * @return the value of student.update_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.update_id
     *
     * @param updateId the value for student.update_id
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.del_state
     *
     * @return the value of student.del_state
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Boolean getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.del_state
     *
     * @param delState the value for student.del_state
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setDelState(Boolean delState) {
        this.delState = delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.payment
     *
     * @return the value of student.payment
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.payment
     *
     * @param payment the value for student.payment
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.compony
     *
     * @return the value of student.compony
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getCompony() {
        return compony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.compony
     *
     * @param compony the value for student.compony
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setCompony(String compony) {
        this.compony = compony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.work_type
     *
     * @return the value of student.work_type
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.work_type
     *
     * @param workType the value for student.work_type
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setWorkType(String workType) {
        this.workType = workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.off_job
     *
     * @return the value of student.off_job
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getOffJob() {
        return offJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.off_job
     *
     * @param offJob the value for student.off_job
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setOffJob(String offJob) {
        this.offJob = offJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.in_school_name
     *
     * @return the value of student.in_school_name
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getInSchoolName() {
        return inSchoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.in_school_name
     *
     * @param inSchoolName the value for student.in_school_name
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setInSchoolName(String inSchoolName) {
        this.inSchoolName = inSchoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.highest_degree
     *
     * @return the value of student.highest_degree
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getHighestDegree() {
        return highestDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.highest_degree
     *
     * @param highestDegree the value for student.highest_degree
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setHighestDegree(String highestDegree) {
        this.highestDegree = highestDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.major
     *
     * @return the value of student.major
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.major
     *
     * @param major the value for student.major
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.school
     *
     * @return the value of student.school
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.school
     *
     * @param school the value for student.school
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.occupation
     *
     * @return the value of student.occupation
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.occupation
     *
     * @param occupation the value for student.occupation
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.process
     *
     * @return the value of student.process
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public Integer getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.process
     *
     * @param process the value for student.process
     *
     * @mbggenerated Mon May 08 16:24:44 CST 2017
     */
    public void setProcess(Integer process) {
        this.process = process;
    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", gender=" + gender +
                ", birthday=" + birthday +
                ", bloodType='" + bloodType + '\'' +
                ", constellation='" + constellation + '\'' +
                ", religion='" + religion + '\'' +
                ", fatherName='" + fatherName + '\'' +
                ", motherName='" + motherName + '\'' +
                ", fatherBirthday=" + fatherBirthday +
                ", motherBirthday=" + motherBirthday +
                ", telephone='" + telephone + '\'' +
                ", mobile='" + mobile + '\'' +
                ", infoSource='" + infoSource + '\'' +
                ", emergencyContact='" + emergencyContact + '\'' +
                ", emergencyContactPhone='" + emergencyContactPhone + '\'' +
                ", qq='" + qq + '\'' +
                ", email='" + email + '\'' +
                ", wechat='" + wechat + '\'' +
                ", identityCard='" + identityCard + '\'' +
                ", ancestralHome='" + ancestralHome + '\'' +
                ", vehicle='" + vehicle + '\'' +
                ", address='" + address + '\'' +
                ", postCode='" + postCode + '\'' +
                ", costSource='" + costSource + '\'' +
                ", computerBasis='" + computerBasis + '\'' +
                ", softBasis='" + softBasis + '\'' +
                ", computerOperate='" + computerOperate + '\'' +
                ", languageSkill='" + languageSkill + '\'' +
                ", expectation='" + expectation + '\'' +
                ", classTeacherId=" + classTeacherId +
                ", classId=" + classId +
                ", hobby='" + hobby + '\'' +
                ", counselorId=" + counselorId +
                ", recordNumber='" + recordNumber + '\'' +
                ", createTime=" + createTime +
                ", createId=" + createId +
                ", updateTime=" + updateTime +
                ", updateId=" + updateId +
                ", delState=" + delState +
                ", payment=" + payment +
                ", compony='" + compony + '\'' +
                ", workType='" + workType + '\'' +
                ", offJob='" + offJob + '\'' +
                ", inSchoolName='" + inSchoolName + '\'' +
                ", grade='" + grade + '\'' +
                ", highestDegree='" + highestDegree + '\'' +
                ", major='" + major + '\'' +
                ", school='" + school + '\'' +
                ", occupation='" + occupation + '\'' +
                ", process=" + process +
                '}';
    }
}